#!/usr/bin/env bash
#
# install-xray.sh — put the VLESS/REALITY service on this node, next to the
# vpn.io server. Run as root, on the VPS.
#
#   sudo bash install-xray.sh
#
#   curl -fL <raw-url>/install-xray.sh -o install-xray.sh
#   sudo bash install-xray.sh
#
# Options:
#   --ref REF          branch or tag to fetch the unit files from (default: main)
#   --skip-firewall    don't touch ufw
#   --dry-run          print what would change and exit
#
# It installs the upstream Xray-core binary, its geo data, a dedicated service
# user and the vpn-xray unit — and stops there if the node has no REALITY
# config yet: the keys are generated by vpn-vless (see docs/VLESS.md), and a
# service with no config must not be started. A node without config simply does
# not run the second service, which is the correct failure.
#
# It does NOT touch vpn-server, its TUN device, its NAT rule or its port. The
# two services share only the machine: this one listens on 443 and proxies from
# the node's own stack, so it needs no forwarding and no subnet of its own.
#
# Re-running is safe: every step checks the current state first, and the binary
# is replaced only when the pinned version actually differs.
set -euo pipefail

# Xray-core is pinned and checksummed rather than "latest": this is the code
# that terminates a public listener, so which bytes land here is a decision, not
# whatever upstream published this morning. Same policy as the Wintun driver in
# the Windows installer.
#
# To bump: pick the tag, take SHA2-256 from the release's .dgst file
#   curl -fsSL https://github.com/XTLS/Xray-core/releases/download/<tag>/Xray-linux-64.zip.dgst
# and update all three constants together.
XRAY_VERSION="v26.3.27"
XRAY_SHA256_AMD64="23cd9af937744d97776ee35ecad4972cf4b2109d1e0fe6be9930467608f7c8ae"
XRAY_SHA256_ARM64="4d30283ae614e3057f730f67cd088a42be6fdf91f8639d82cb69e48cde80413c"

SERVICE_USER="vpn-xray"
BOT_USER="vpn-bot"
CONF_DIR="/etc/vpn-xray"
DATA_DIR="/usr/local/share/xray"
BIN="/usr/local/bin/xray"
LISTEN_PORT="443"

REPO="sodazzzzzz/vpn.io"
REF="main"
SKIP_FIREWALL=0
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --ref)           REF="${2:?--ref needs a branch or tag}"; shift 2 ;;
    --skip-firewall) SKIP_FIREWALL=1; shift ;;
    --dry-run)       DRY_RUN=1; shift ;;
    -h|--help)       sed -n '2,25p' "$0"; exit 0 ;;
    *) echo "unknown option: $1 (try --help)" >&2; exit 2 ;;
  esac
done

say()  { echo "==> $*"; }
skip() { echo "    already done: $*"; }
run()  { if [ "$DRY_RUN" = 1 ]; then echo "    would run: $*"; else "$@"; fi; }

[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }
[ "$(uname -s)" = Linux ] || { echo "this installs a Linux node service (detected $(uname -s))" >&2; exit 1; }
command -v systemctl >/dev/null || { echo "systemd is required" >&2; exit 1; }
command -v apt-get   >/dev/null || { echo "this script targets Debian/Ubuntu (apt-get not found)" >&2; exit 1; }

# One scratch directory for everything this script downloads, removed on any
# exit. (Two traps would not do: the second replaces the first and leaks the
# first directory.)
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

case "$(uname -m)" in
  x86_64|amd64)  asset="Xray-linux-64.zip";          want="$XRAY_SHA256_AMD64" ;;
  aarch64|arm64) asset="Xray-linux-arm64-v8a.zip";   want="$XRAY_SHA256_ARM64" ;;
  *) echo "unsupported architecture $(uname -m) — only amd64 and arm64 are pinned here" >&2; exit 1 ;;
esac

here_early="$(cd "$(dirname "$0")" && pwd)"
raw_early="https://raw.githubusercontent.com/$REPO/$REF/packaging/server"

say "packages"
missing=""
for pkg in curl unzip; do
  command -v "$pkg" >/dev/null || missing="$missing $pkg"
done
if [ -n "$missing" ]; then
  # shellcheck disable=SC2086  # word splitting is what we want for the package list
  run sh -c "apt-get update -qq && apt-get install -y -qq$missing"
else
  skip "curl, unzip present"
fi

say "Xray-core $XRAY_VERSION"
installed=""
if [ -x "$BIN" ]; then
  # `xray version` prints e.g. "Xray 26.3.27 (Xray, Penetrates Everything.) ...";
  # compare against the tag without its leading v.
  installed="$("$BIN" version 2>/dev/null | head -n1 | awk '{print $2}')" || installed=""
fi
if [ "$installed" = "${XRAY_VERSION#v}" ]; then
  skip "Xray ${XRAY_VERSION#v} installed"
elif [ "$DRY_RUN" = 1 ]; then
  echo "    would download and verify $asset, then install $BIN"
else
  curl -fSL --retry 3 -o "$tmp/$asset" \
    "https://github.com/XTLS/Xray-core/releases/download/$XRAY_VERSION/$asset"
  # Fail closed: a mismatch means the bytes are not the release we pinned, and
  # nothing is installed. The checksum lives in this script (which arrives over
  # a signed release), not next to the download.
  got="$(sha256sum "$tmp/$asset" | cut -d' ' -f1)"
  if [ "$got" != "$want" ]; then
    echo "checksum mismatch for $asset" >&2
    echo "  want $want" >&2
    echo "  got  $got" >&2
    exit 1
  fi
  say "checksum ok"
  unzip -q -o "$tmp/$asset" -d "$tmp/x"
  install -m 0755 "$tmp/x/xray" "$BIN"
  install -d -m 0755 "$DATA_DIR"
  install -m 0644 "$tmp/x/geoip.dat" "$tmp/x/geosite.dat" "$DATA_DIR/"
  echo "    installed $BIN ($("$BIN" version 2>/dev/null | head -n1))"
fi

say "service user"
if id "$SERVICE_USER" >/dev/null 2>&1; then
  skip "user $SERVICE_USER exists"
else
  # No home, no shell, no login: this account exists only to own the config and
  # run one daemon.
  run useradd --system --no-create-home --home-dir /nonexistent --shell /usr/sbin/nologin "$SERVICE_USER"
fi

say "config directory"
if [ -d "$CONF_DIR" ]; then
  skip "$CONF_DIR exists"
else
  run install -d -m 2770 -o "$SERVICE_USER" -g "$SERVICE_USER" "$CONF_DIR"
fi
# The private key and the client UUIDs live here, so tighten the directory even
# when it predates this script (an operator may have created it by hand).
#
# 2770, not 0700: two accounts write here — the service reads the config, and
# vpn-bot issues and revokes access. The setgid bit makes a file created by
# either of them (or by root running the CLI) inherit the group, so the other
# can still read and replace it. Everyone else on the box is kept out by the
# directory, which is the only boundary that matters for a directory of keys.
run chown "$SERVICE_USER:$SERVICE_USER" "$CONF_DIR"
run chmod 2770 "$CONF_DIR"

# The bot writes the client list; without membership it could not, and every
# invite would fail at the last step. Skipped silently when the bot is not
# installed on this node.
if id "$BOT_USER" >/dev/null 2>&1; then
  if id -nG "$BOT_USER" | tr ' ' '\n' | grep -qx "$SERVICE_USER"; then
    skip "$BOT_USER is in the $SERVICE_USER group"
  else
    say "granting $BOT_USER access to $CONF_DIR"
    run usermod -aG "$SERVICE_USER" "$BOT_USER"
    echo "    restart vpn-bot for the new group to take effect"
  fi
fi

say "apply helper"
apply_dir="/usr/local/lib/vpn-xray"
apply_src="$here_early/apply-config.sh"
if [ ! -f "$apply_src" ]; then
  if [ "$DRY_RUN" = 1 ]; then
    echo "    would fetch apply-config.sh from $raw_early"
  else
    say "fetching apply-config.sh"
    apply_src="$tmp/apply-config.sh"
    curl -fsSL -o "$apply_src" "$raw_early/apply-config.sh"
  fi
fi
if [ "$DRY_RUN" = 1 ]; then
  echo "    would install $apply_dir/apply-config.sh"
elif cmp -s "$apply_src" "$apply_dir/apply-config.sh"; then
  skip "apply-config.sh up to date"
else
  run install -d -m 0755 "$apply_dir"
  run install -m 0755 "$apply_src" "$apply_dir/apply-config.sh"
fi

say "units"
here="$here_early"
# Fetch the units when this script was downloaded on its own rather than copied
# with the repo — the same thing provision.sh does for the NAT helpers, because
# "curl one file and run it" is how these scripts actually reach a node.
raw="$raw_early"
reload=0
for unit in vpn-xray.service vpn-xray-reload.service vpn-xray-reload.path; do
  src="$here/$unit"
  if [ ! -f "$src" ]; then
    if [ "$DRY_RUN" = 1 ]; then
      echo "    would fetch $unit from $raw"
      continue
    fi
    say "fetching $unit"
    src="$tmp/$unit"
    curl -fsSL -o "$src" "$raw/$unit"
  fi
  if cmp -s "$src" "/etc/systemd/system/$unit"; then
    skip "$unit up to date"
  else
    run install -m 0644 "$src" "/etc/systemd/system/$unit"
    reload=1
  fi
done
[ "$reload" = 0 ] || run systemctl daemon-reload

# The path unit is how a change reaches the running service: it watches the
# config and restarts Xray when it changes, so the unprivileged writer never
# needs the right to restart anything. Enable it even before there is a config —
# it costs nothing and is one less thing to remember later.
if systemctl is-enabled vpn-xray-reload.path >/dev/null 2>&1; then
  skip "vpn-xray-reload.path enabled"
else
  run systemctl enable --now vpn-xray-reload.path
fi

if [ "$SKIP_FIREWALL" = 0 ] && command -v ufw >/dev/null && ufw status 2>/dev/null | grep -q '^Status: active'; then
  if ufw status | grep -q "^${LISTEN_PORT}/tcp"; then
    skip "ufw already allows ${LISTEN_PORT}/tcp"
  else
    say "firewall"
    run ufw allow "${LISTEN_PORT}/tcp"
  fi
fi

echo
if [ -s "$CONF_DIR/config.json" ]; then
  say "config present — starting"
  run systemctl enable --now vpn-xray
  run systemctl restart vpn-xray
  echo
  echo "Second service is installed and running (Xray-core $XRAY_VERSION)."
  echo "Check it:  systemctl status vpn-xray   |   journalctl -u vpn-xray -f"
else
  cat <<EOF
Xray-core is installed but NOT started: this node has no REALITY config yet.

Generate one (keys stay on this node — they are not part of any release):

    vpn-update --force                 # brings vpn-vless onto this node
    vpn-vless init -address <this-node-public-address>

Then add someone and start the service:

    vpn-vless add <name>
    systemctl enable --now vpn-xray

See docs/VLESS.md for choosing the site this node masquerades as.
EOF
fi
