#!/usr/bin/env bash
#
# install-xray.sh — put the VLESS/REALITY service on this node, next to the
# vpn.io server. Run as root, on the VPS.
#
#   sudo bash install-xray.sh
#
# Options:
#   --skip-firewall    don't touch ufw
#   --dry-run          print what would change and exit
#
# It installs the upstream Xray-core binary, its geo data, a dedicated service
# user and the vpn-xray unit — and stops there if the node has no REALITY
# config yet: the keys are generated by vpn-vless (see docs/VLESS.md), and a
# service with no config must not be started. A node without config simply does
# not run the second service, which is the correct failure.
#
# It does NOT touch vpn-server, its TUN device, its NAT rule or its port. The
# two services share only the machine: this one listens on 443 and proxies from
# the node's own stack, so it needs no forwarding and no subnet of its own.
#
# Re-running is safe: every step checks the current state first, and the binary
# is replaced only when the pinned version actually differs.
set -euo pipefail

# Xray-core is pinned and checksummed rather than "latest": this is the code
# that terminates a public listener, so which bytes land here is a decision, not
# whatever upstream published this morning. Same policy as the Wintun driver in
# the Windows installer.
#
# To bump: pick the tag, take SHA2-256 from the release's .dgst file
#   curl -fsSL https://github.com/XTLS/Xray-core/releases/download/<tag>/Xray-linux-64.zip.dgst
# and update all three constants together.
XRAY_VERSION="v26.3.27"
XRAY_SHA256_AMD64="23cd9af937744d97776ee35ecad4972cf4b2109d1e0fe6be9930467608f7c8ae"
XRAY_SHA256_ARM64="4d30283ae614e3057f730f67cd088a42be6fdf91f8639d82cb69e48cde80413c"

SERVICE_USER="vpn-xray"
CONF_DIR="/etc/vpn-xray"
DATA_DIR="/usr/local/share/xray"
BIN="/usr/local/bin/xray"
LISTEN_PORT="443"

SKIP_FIREWALL=0
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --skip-firewall) SKIP_FIREWALL=1; shift ;;
    --dry-run)       DRY_RUN=1; shift ;;
    -h|--help)       sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "unknown option: $1 (try --help)" >&2; exit 2 ;;
  esac
done

say()  { echo "==> $*"; }
skip() { echo "    already done: $*"; }
run()  { if [ "$DRY_RUN" = 1 ]; then echo "    would run: $*"; else "$@"; fi; }

[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }
[ "$(uname -s)" = Linux ] || { echo "this installs a Linux node service (detected $(uname -s))" >&2; exit 1; }
command -v systemctl >/dev/null || { echo "systemd is required" >&2; exit 1; }
command -v apt-get   >/dev/null || { echo "this script targets Debian/Ubuntu (apt-get not found)" >&2; exit 1; }

case "$(uname -m)" in
  x86_64|amd64)  asset="Xray-linux-64.zip";          want="$XRAY_SHA256_AMD64" ;;
  aarch64|arm64) asset="Xray-linux-arm64-v8a.zip";   want="$XRAY_SHA256_ARM64" ;;
  *) echo "unsupported architecture $(uname -m) — only amd64 and arm64 are pinned here" >&2; exit 1 ;;
esac

say "packages"
missing=""
for pkg in curl unzip; do
  command -v "$pkg" >/dev/null || missing="$missing $pkg"
done
if [ -n "$missing" ]; then
  # shellcheck disable=SC2086  # word splitting is what we want for the package list
  run sh -c "apt-get update -qq && apt-get install -y -qq$missing"
else
  skip "curl, unzip present"
fi

say "Xray-core $XRAY_VERSION"
installed=""
if [ -x "$BIN" ]; then
  # `xray version` prints e.g. "Xray 26.3.27 (Xray, Penetrates Everything.) ...";
  # compare against the tag without its leading v.
  installed="$("$BIN" version 2>/dev/null | head -n1 | awk '{print $2}')" || installed=""
fi
if [ "$installed" = "${XRAY_VERSION#v}" ]; then
  skip "Xray ${XRAY_VERSION#v} installed"
elif [ "$DRY_RUN" = 1 ]; then
  echo "    would download and verify $asset, then install $BIN"
else
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  curl -fSL --retry 3 -o "$tmp/$asset" \
    "https://github.com/XTLS/Xray-core/releases/download/$XRAY_VERSION/$asset"
  # Fail closed: a mismatch means the bytes are not the release we pinned, and
  # nothing is installed. The checksum lives in this script (which arrives over
  # a signed release), not next to the download.
  got="$(sha256sum "$tmp/$asset" | cut -d' ' -f1)"
  if [ "$got" != "$want" ]; then
    echo "checksum mismatch for $asset" >&2
    echo "  want $want" >&2
    echo "  got  $got" >&2
    exit 1
  fi
  say "checksum ok"
  unzip -q -o "$tmp/$asset" -d "$tmp/x"
  install -m 0755 "$tmp/x/xray" "$BIN"
  install -d -m 0755 "$DATA_DIR"
  install -m 0644 "$tmp/x/geoip.dat" "$tmp/x/geosite.dat" "$DATA_DIR/"
  echo "    installed $BIN ($("$BIN" version 2>/dev/null | head -n1))"
fi

say "service user"
if id "$SERVICE_USER" >/dev/null 2>&1; then
  skip "user $SERVICE_USER exists"
else
  # No home, no shell, no login: this account exists only to own the config and
  # run one daemon.
  run useradd --system --no-create-home --home-dir /nonexistent --shell /usr/sbin/nologin "$SERVICE_USER"
fi

say "config directory"
if [ -d "$CONF_DIR" ]; then
  skip "$CONF_DIR exists"
else
  run install -d -m 0700 -o "$SERVICE_USER" -g "$SERVICE_USER" "$CONF_DIR"
fi
# The private key and the client UUIDs live here, so tighten the directory even
# when it predates this script (an operator may have created it by hand).
run chown "$SERVICE_USER:$SERVICE_USER" "$CONF_DIR"
run chmod 0700 "$CONF_DIR"

say "unit"
here="$(cd "$(dirname "$0")" && pwd)"
unit_src="$here/vpn-xray.service"
[ -f "$unit_src" ] || { echo "vpn-xray.service not found next to this script" >&2; exit 1; }
if cmp -s "$unit_src" /etc/systemd/system/vpn-xray.service; then
  skip "unit up to date"
else
  run install -m 0644 "$unit_src" /etc/systemd/system/vpn-xray.service
  run systemctl daemon-reload
fi

if [ "$SKIP_FIREWALL" = 0 ] && command -v ufw >/dev/null && ufw status 2>/dev/null | grep -q '^Status: active'; then
  if ufw status | grep -q "^${LISTEN_PORT}/tcp"; then
    skip "ufw already allows ${LISTEN_PORT}/tcp"
  else
    say "firewall"
    run ufw allow "${LISTEN_PORT}/tcp"
  fi
fi

echo
if [ -s "$CONF_DIR/config.json" ]; then
  say "config present — starting"
  run systemctl enable --now vpn-xray
  run systemctl restart vpn-xray
  echo
  echo "Second service is installed and running (Xray-core $XRAY_VERSION)."
  echo "Check it:  systemctl status vpn-xray   |   journalctl -u vpn-xray -f"
else
  cat <<EOF
Xray-core is installed but NOT started: this node has no REALITY config yet.

Generate one (keys stay on this node — they are not part of any release):

    vpn-vless init -address <this-node-public-address>

Then add someone and start the service:

    vpn-vless add <name>
    systemctl enable --now vpn-xray

See docs/VLESS.md for choosing the site this node masquerades as.
EOF
fi
