// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {control} from '../models';

export function Connect(arg1:control.Credentials):Promise<control.Connected>;

export function Disconnect():Promise<void>;

export function Status():Promise<control.Status>;
