// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {control} from '../models';

export function Connect(arg1:main.ConnectForm):Promise<control.Connected>;

export function Disconnect():Promise<void>;

export function ImportProfileBundle():Promise<main.ProfileInfo>;

export function PickCredential(arg1:string):Promise<main.CredInfo>;

export function Profile():Promise<main.ProfileInfo>;

export function Reconnect():Promise<control.Connected>;

export function Status():Promise<control.Status>;
